### ISSUE TITLE
The extension changes its own template when editing setting.json

### ISSUE THREAD

**Issue by GZTimeWalker** [EPIVISION/vscode-file-header#8]
When editing setting.json, the extension changes its own template, causing setting.json to not save properly.

Maybe it needs to check if the file is a Settings file, or change another way to specify whether the file needs to be updated?

**Comment by 5P5** [comment]
Hello, can you please elaborate?
What are your Power Header setting?
How does the _setting.json_ file look like and what exactly gets changed when?

**Comment by GZTimeWalker** [comment]
> Hello, can you please elaborate? What are your Power Header setting? How does the _setting.json_ file look like and what exactly gets changed when?

Here's an example:

`setting.json` is set to the following content...

```json 
{
  "powerHeader.template": "Modified: !date!\\n",
  "powerHeader.autoInsert.enable": true,
  "powerHeader.update.enable": "save"
}
```

Then, when I try to save the file, it turns into...

```json
{
  "powerHeader.template": "Modified: 2022-01-28T15:10:21.364Z
  "powerHeader.autoInsert.enable": true,
  "powerHeader.update.enable": "save"
}
```

It breaks the format of JSON when I edit the `settings.json`, so maybe you need to add some excluded files?

**Comment by 5P5** [comment]
Thank you. I understand your problem now. 

This is actually working as designed 😉 
As said, the *Header Content Update* is just using a JavaScript regular expression replace on the first match. **Use with caution**

Your `"powerHeader.template": "Modified: !date!\\n",` line just happens to match the default regex `Modified:\s+(.+)` and you auto-update on save, so it will be replaced.

To fix this unfortunate coincidence, you have multiple option:
1. Edit and save _settings.json_ only with another external program (e.g. notepad.exe) 🤪
2. Disable the *Header Content Update* in all jsonc files `"[jsonc]": {"powerHeader.update.enable": "disable"},`
- As a more practical solution you can simply add modified regex to your _settings.json_ and keep using this awesome feature.
Choices are:
1. `"powerHeader.update.content": ["^Modified:\\s+(.+)=!date!"],` to only match lines beginning with `Modified:`
2. `"powerHeader.update.content": ["[^\"]Modified:\\s+(.+)=!date!"],` to not match on the `"Modified:`-line (the one with the quote in _settings.json_ file, in case you have leading spaces in your file headers, etc.)

In order to get this new settings line in the file and "un-break" your existing _settings.json_ you will have to: insert, save, undo, save.

Please let me know you result 😃

**Comment by 5P5** [comment]
Thank you. I understand your problem now. 

This is actually working as designed 😉 
As said, the *Header Content Update* is just using a JavaScript regular expression replace on the first match. **Use with caution**

Your `"powerHeader.template": "Modified: !date!\\n",` line just happens to match the default regex `Modified:\s+(.+)` and you update on save, so it will be replaced.

To fix this unfortunate coincidence, you have multiple option:
1. Edit and save _settings.json_ only with another external program (e.g. notepad.exe) 🤪
2. Disable the *Header Content Update* in all jsonc files: `"[jsonc]": {"powerHeader.update.enable": "disable"},`
3. As a more practical solution, you can simply modify the "powerHeader.template" in your _settings.json_ so that the regex will not match there and keep using this awesome feature: `"powerHeader.template": "Modified:\0 !date!\\n",` (yes, this is dirty hack and I'm amazed it works)

Please let me know your result 😃

**Comment by 5P5** [comment]
Thank you. I understand your problem now. 

This is actually working as designed 😉 
As said, the *Header Content Update* is just using a JavaScript regular expression replace on the first match. **Use with caution**

Your `"powerHeader.template": "Modified: !date!\\n",` line just happens to match the default regex `Modified:\s+(.+)` and you update on save, so it will be replaced.

To fix this unfortunate coincidence, you have multiple option:
1. Edit and save _settings.json_ only with another external program (e.g. notepad.exe) 🤪
2. Disable the *Header Content Update* in all jsonc files: `"[jsonc]": {"powerHeader.update.enable": "disable"},`
3. Set `"powerHeader.update.enable": "manual",` and not update in the _settings.json_
3. As a **workaround**, you can modify the "powerHeader.template" in your _settings.json_ so that the regex will not match there and keep using this awesome feature: `"powerHeader.template": "Modified:\0 !date!\\n",` 

Yes, this is dirty hack and I'm amazed it works.
However, vscode will complain
> Unable to write into settings. Please open the settings to correct errors/warnings in the file and try again.
###### Invalid escape character in string.jsonc(261)
and not save _settings.json_ when modified from the Settings GUI. You can still change and save from the "Open Settings (JSON)" file itself.

I might add some logic to bypass this problem in a future version.
